### ISSUE TITLE
Electron app packaging ia32 error

### ISSUE THREAD

**Issue by qzgyw** [jitsi/robotjs#18]
I use electron-builder to package electron applications, normal use of x64, ia32 cannot be packaged, there is a problem with the precompiled script of ia32? Is there any precompiled package compatible with both ia32 and x64?

this is the log：
```javascript
INFO  Building app with electron-builder:
  • electron-builder  version=22.14.13 os=10.0.19044
  • writing effective config  file=dist_electron\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=@jitsi/robotjs@0.6.13 platform=win32 arch=ia32
  • rebuilding native dependency  name=@jitsi/robotjs version=0.6.13
  ⨯ cannot execute  cause=exit status 1
$ node-gyp-build
......
```

##  Environment

* RobotJS version: 0.6.13
* Node.js version: 16.14.0
* npm version:8.3.1
* Operating System:10.0.19044

**Comment by qzgyw** [comment]
Sorry, I executed "node-gyp rebuild" to repackage, the build was successful, the issue is closed, thank you!

**Comment by hanxiang-li** [comment]
Can you take a look at the executed packaging command?
